sudo: required

language: java

services:
- docker

env:
  global:
    - env:
    - PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin/:$PATH
    - JENKINS_URL=https://ci2.mycoachfootball.com
    - secure: "ocNes84Dmjl+Pjl5ZLM3Bm4/z5W39veG3gf7PJUEE+EBeA6W79rkRuzsrh7aO9l53gP5AQnwIo7C2VT842Xfnx6r8sR8cwu3ebhDnWamnU0yg9L8JzFZX56N+BtFya6OQZZFBXYg4fdvE74hiqflNDd4hLR/FPbPq1vOd1WLNUtiYK+0H5FaKcodVsZtZ4x+ghytugtFBCdUGctNFHmCIUiHIF4qhLdDc2lnKpN/MGyz4Q5N/pRy4jnf9mmTPDL+uL96M9s4LwubG8nsb7nBA6UL0i0+zLGOeqP63ZmqlGZTny/omOpbHSmtybB1pee6WE0ut4YxNd4lYHWL6F/ZlRPFbv4VPCpAprJhOKW9npRegDfT9+exjs5wwQAY+ebCN05OahkBDEZ2VSLnR/uT0W4dDSUMEbBLOnXwzEUBTxvnes+58APis3IzDJmJbXCUh0NmDJTiEfUt7JdkxsMIV7In7F1DHaAkGSJcmbTmJ53VrhmE+VtEQuEPjcQPd+OR7AmVWzppsgPLp16tP4PybMgcX1ry32/Dggwx/J1ZE+xFeAv3Tkl99t1oDjxW9ky5NV1GKFnp+27k7nMhfIU3jY2VpMG5Jha3rjacxLQQvjZREw/2iq6Sagc4qpxMo5eeOvsFljGbiDRZWo3SOVqPVhPOg5aysgUXeB5+diLNt3k=" # JENKINS_USER
    - secure: "bK8xnxADh64v/AytW9uIu5B/5TbJi0aDstnQCZ7B+MJlFab03iphDAwTILOs2g19FMxjhvFGCy5Gfv5lirbbQCEpoQPu15qFThYlGcvliLnGD8kkiPwnqCwweKi0K/8JhsyW47WsvkZofQItM7Z7xBmm10UVDsLCfrqq7ilcwBe+kho6wYJdjuGeg9dfRmq7Z6IlF9TfZxEvsW+oC+sjPEoSO3bzdm765B+c1Ju77xz7IJO7f6faxHbdNEIdpbIyz2uCZtvL2eNimsGya80bnPc16Rjc95PMKwtQf0JW8SnCfB2sWe/07stDc56P44G5BBRBNzTSn8uAc9qsB3ehev5+tL7aZLL1xknZM0O1fE1IJuh2EvoypeWT7Y0xpvhcFNNdV4vAaYrfop7/dKtEjuZoXh7695WZ3I0owxnShlsnHqGIZt8joMYtUguWidp3d69VFRYGtmJJQOd7giuSkRsPc2iluS2Je7+rv/POWkOJjFavFq5ykF04Nmk9uVElUxuFBJjDqioH9kWVkpHVS03y4gfwLefbnVn0/kXZR3XBntJKZeljTU0M7SSx1sc5yLhJeZdGF5zOpZjMAk2K8ApWbvFJjteH0SOXZ7i5pyAG1W2NnPFjgx2iSnTNS4UALXYh9YLSs7hvQnepjkKwKJUT4Q6YHIQ73tr5mW7jOBw=" # JENKINS_API_KEY

before_script:
  - openssl version
  - openssl aes-256-cbc -K $encrypted_eca80537ee67_key -iv $encrypted_eca80537ee67_iv -in settings.tar.gz.enc -out settings.tar.gz -d
  - tar zxf secrets.tar.gz
  - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
  - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz

script:
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u _json_key -p "$(cat ./travis-docker-push.json)" https://eu.gcr.io
      mvn --settings settings.xml install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    elif [[ "$TRAVIS_BRANCH" == "develop" ]]; then
      mvn --settings settings.xml test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      mvn compile jib:dockerBuild -Dimage=maxwelldaemonnats:develop
      ./trivy --exit-code 1 --severity CRITICAL --ignore-unfixed --no-progress maxwelldaemonnats:develop
    else
      mvn --settings settings.xml test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    fi

after_success:
- |
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    curl -X POST --user $JENKINS_USER:$JENKINS_API_KEY "$JENKINS_URL/job/Bump%20something%20in%20qa/buildWithParameters?THING_TO_BUMP=maxwelldaemonnats&NEW_VERSION=$version"
  elif [[ "$TRAVIS_BRANCH" == "develop" && "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_COMMIT_MESSAGE" != "Bump version to"* ]]; then
    curl -X POST --user $JENKINS_USER:$JENKINS_API_KEY $JENKINS_URL'/job/Release%20maxwelldaemonnats/buildWithParameters'
  fi

# Don't build version tags
branches:
  except:
    - /^v[0-9]+\.[0-9]{1,2}\.[0-9]{1,2}$/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete